services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: all-strategy-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
        environment:
            APP_ENV: local
            APP_DEBUG: "true"
        networks:
            - all-strategy-network

    database:
        image: mysql:8.0
        container_name: all-strategy-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - all-strategy-network

networks:
    all-strategy-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
